// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE53O1zNjQGARLBqaHCqwYd9bHVHhYdsw',
    appId: '1:992997612782:web:2c88c32d1c5ad31554a7ff',
    messagingSenderId: '992997612782',
    projectId: 'hw4-message-board-app-18242',
    authDomain: 'hw4-message-board-app-18242.firebaseapp.com',
    storageBucket: 'hw4-message-board-app-18242.firebasestorage.app',
    measurementId: 'G-PFTFL4VF14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_zEQKT-sG3E2_k9PcaTPXWL9VNivFyE',
    appId: '1:992997612782:android:7abf71fda026ce8754a7ff',
    messagingSenderId: '992997612782',
    projectId: 'hw4-message-board-app-18242',
    storageBucket: 'hw4-message-board-app-18242.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPOOaurog77x5Cksl6UO9S0GQdMc61tWw',
    appId: '1:992997612782:ios:00dba6b38d25629154a7ff',
    messagingSenderId: '992997612782',
    projectId: 'hw4-message-board-app-18242',
    storageBucket: 'hw4-message-board-app-18242.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPOOaurog77x5Cksl6UO9S0GQdMc61tWw',
    appId: '1:992997612782:ios:00dba6b38d25629154a7ff',
    messagingSenderId: '992997612782',
    projectId: 'hw4-message-board-app-18242',
    storageBucket: 'hw4-message-board-app-18242.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE53O1zNjQGARLBqaHCqwYd9bHVHhYdsw',
    appId: '1:992997612782:web:343f69deb2db076254a7ff',
    messagingSenderId: '992997612782',
    projectId: 'hw4-message-board-app-18242',
    authDomain: 'hw4-message-board-app-18242.firebaseapp.com',
    storageBucket: 'hw4-message-board-app-18242.firebasestorage.app',
    measurementId: 'G-2GB0QT0H3N',
  );
}
